name: Build

on:
  push:
    branches: [ master ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore: '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DISTRO: [focal, focal_cuda11.2, focal_llvm, focal_cuda11.2_llvm, jammy, jammy_cuda11.8, jammy_llvm, jammy_cuda11.8_llvm]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Docker login
        continue-on-error: true
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          file: ${{github.workspace}}/docker/${{ matrix.DISTRO }}/Dockerfile
          context: .
          push: false
